### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by mckellyln**
@radssh various updates I find helpful, for your review; and thanks for the help and for awesome radssh :-)

### CODE REVIEW

**Comment by mckellyln** [comment]
@radssh when you have time

**Comment by radssh** [comment]
The modifications to console.py - did you not wrap those up into a formatter plugin to get working?

**Comment by mckellyln** [comment]
Hi.

>> did you not wrap those up into a formatter plugin ?

No, I just updated the default hash algo to work better for IPs or hostnames.

Is distro.linux_distribution() better than platform.dist() ?

**Comment by mckellyln** [comment]
I thought I needed to add *tty1, as in -
```
star_commands = {'*tty': radssh_tty, '*tty1': radssh_tty}
```

**Comment by radssh** [comment]
> > > did you not wrap those up into a formatter plugin ?
> 
> No, I just updated the default hash algo to work better for IPs or hostnames.

I made the console formatter call extensible via plugins, and added your IP based formatter to the core_plugins/formatters.py. You should be able to enable your preferred behavior by setting `console.formatter=formatters.ip_colorizer` in your ~/.radssh_config file. Other examples included there are `ansi256` and `ansi256_rj` that will expand the default palette to the ANSI 256 color range, with the _rj variant placing the host labels right justified instead of left justified, based on console width.  I thought I notified you directly when that update was released... 😔

**Comment by radssh** [comment]
> Hi.
> 
> > > did you not wrap those up into a formatter plugin ?
> 
> No, I just updated the default hash algo to work better for IPs or hostnames.
> 
> Is distro.linux_distribution() better than platform.dist() ?

They are both no longer available - I merged in the change from @eorochena and will be patching it up to not require `distro` as a hard dependency.

**Comment by radssh** [comment]
as far as *tty1 goes, I think having the config option to auto_tty, the logic can be fully integrated into plain *tty -- if there's only a single (active) host in the cluster and auto_tty is True, then bypass the pause/prompt  and dive right in.  You think that would do the trick?

**Comment by mckellyln** [comment]
ok, sure I agree.  I called *tty1 - I will change it to be *tty again, and then change the logic for checking **tty1 to be if only 1 host and auto_tty set ...

**Comment by mckellyln** [comment]
ok, I will test out the formatter and remove the console.py change from the PR

**Comment by radssh** [comment]
And with the formatter-as-plugin capability, you have liberty to fully fine-tune the hashing/formatting of the output lines based on any criteria and easy to experiment with - just define a function in a plugin .py file that takes (tag, text) , where tag is a pair (label, hilight), and text as a (possibly) multi-line chunk of output. The function should `yield` formatted output lines based on the called input.

**Comment by mckellyln** [comment]
formatters.py has:
```
def ip_hash(hstr0):
    '''Improved hashing when dealing with consecutive IP addresses'''
    hstr1 = re.sub('[^0-9]', '.', hstr0)
    hstr2 = hstr1.replace(".", "0")
    hstr = hstr2[-3:]
    hval = int(hstr)
    return hval
```
but my newer hash is:
```
def hsum(hstr0):
    temp = "0"
    Sum = 0
    for ch in hstr0:
        if (ch.isdigit()):
            temp += ch
        else:
            Sum += int(temp)
            temp = "0"
    return Sum + int(temp)

def myhash(hstr0):
    hstr = ''.join([n for n in hstr0 if n.isdigit()])
    if len(hstr) == 0:
        return hash(hstr0)
    else:
        return hsum(hstr0)
```
which works well with IP and names.  Can I add this as my own plugin and point to it ?  I think you are saying yes.

**Comment by mckellyln** [comment]
@radssh I think you did mention something about the colorizer extensibility a while back.
I was just trying to improve the default one and I forgot about that, sorry.
But I can do that now via the console.formatter setting.

**Comment by radssh** [comment]
You'll need to provide a function like colorize_ip or ansi256 in the examples. It's not just a hash function, but gives you full control of mapping text-based output (with tag of source and hilight(stderr)) into a formatted string with embedded ansi codes. Conventionally, the host label is used to map its hash value into a color picker, but if you were customizing into displaying log file entries, you could colorize based on the log message severity, or timestamp value, not just the hostname/label.

**Comment by radssh** [comment]
Changed the configuration option name, and pushed 953b091e166b53f51921ce6bd5f659eae9bc054f for the new `ordered_placeholder` option. Please review.

**Comment by radssh** [comment]
More changes as I merge in these features - f5053dae35a4cbaf1406540117a697953bd3ae76 handles the tty_init_file as `plugin.star_tty.rc_file`. I reworked some of the plugin handling so that the settings get applied prior to the `init()` call. The plugin will  read the contents one time, into its own local settings dict.
Like .rc file execution, the commands are (attempted to be) run quietly, before the user is dropped into the `posix_shell()`, the queued output is read and discarded. May need to do this more elaborately than a short sleep, single read, but for what I except from most .rc files, this should do for a majority of cases.

**Comment by radssh** [comment]
@mckellyln - I'm deferring only the sftp session portion of this MR as stated in #50. The rest, I have merged in, with various adaptations for consistency and some option renaming. Please review the chain of recent commits, and feel free to continue the dialog on any as per-commit comments. Appreciate the contributions and ideas. 👍

**Pull request closed without merging**
